// ignore_for_file: depend_on_referenced_packages, avoid_print

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// This file is auto-generated by FlutterFire CLI.
/// Replace the placeholder values with your actual Firebase project configuration.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEGTM8KH1Nuf3JPkd8wijY_uEDa0wtxPY',
    appId: '1:844686321044:android:257856a3610576c63f9b81',
    messagingSenderId: '844686321044',
    projectId: 'gymbt-4ef87',
    storageBucket: 'gymbt-4ef87.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX4BVFnNSOcMN3ME7111-FllNCY_oscK0',
    appId: '1:844686321044:ios:85d71d1fe64ae0f23f9b81',
    messagingSenderId: '844686321044',
    projectId: 'gymbt-4ef87',
    storageBucket: 'gymbt-4ef87.firebasestorage.app',
    iosBundleId: 'com.gymbt.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeVdBsIpGBTm9x2NlQKJKKarLRMmEVv3U',
    appId: '1:844686321044:web:fbedc9ce24285d303f9b81',
    messagingSenderId: '844686321044',
    projectId: 'gymbt-4ef87',
    authDomain: 'gymbt-4ef87.firebaseapp.com',
    storageBucket: 'gymbt-4ef87.firebasestorage.app',
    measurementId: 'G-5S5DTPH3QF',
  );
}
